name: ur_provider
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-356.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  http: ^0.13.6
  cupertino_icons: ^1.0.2
  logger: ^1.0.0
  carousel_slider: 4.1.1
  #camera: ^0.10.3+2
  #  image_cropper: ^1.0.2
  image_picker: ^0.8.6+4
  photo_view: ^0.14.0
  #  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  path: ^1.8.2
  shared_preferences: ^2.1.1
  flutter_launcher_icons: ^0.13.0
  flutter_image_compress: ^1.1.3
  flutter_dotenv: ^5.1.0
  go_router: ^6.2.0
  google_fonts: ^4.0.4
  dio: ^5.1.2
  flutter_riverpod: ^2.3.6
  formz: ^0.6.0
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - .env
    - assets/loaders/
    - assets/images/