// Generated by https://quicktype.io
import 'package:ur_provider/features/auth/domain/domain.dart';

class Product {
  int id;
  String name;
  String category;
  String image;
  int price;
  String description;
  int numberOfSales;
  bool available;
  int supplierId;
  int rating;

  Product({
    required this.id,
    required this.name,
    required this.category,
    required this.image,
    required this.price,
    required this.description,
    required this.numberOfSales,
    required this.available,
    required this.supplierId,
    required this.rating,
  });
}
