// Generated by https://quicktype.io
import 'package:ur_provider/features/auth/domain/domain.dart';

class Supplier {
  int id;
  String supplierName;
  String name;
  String lastName;
  String email;
  String address;
  int ruc;
  String category;
  String description;
  int phone;
  String password;
  String image;
  int likes;

  Supplier({
    required this.id,
    required this.supplierName,
    required this.name,
    required this.lastName,
    required this.email,
    required this.address,
    required this.ruc,
    required this.category,
    required this.description,
    required this.phone,
    required this.password,
    required this.image,
    required this.likes,
  });
  static Supplier objJson(Map<String, dynamic> json) {
    return Supplier(
      id: json["id"] as int,
      supplierName: json["supplierName"] as String,
      name: json["name"] as String,
      lastName: json["lastName"] as String,
      email: json["email"] as String,
      address: json["address"] as String,
      ruc: json["ruc"] as int,
      category: json["category"] as String,
      description: json["description"] as String,
      phone: json["phone"] as int,
      password: json["password"] as String,
      image: json["image"] as String,
      likes: json["likes"] as int,
    );
  }
}
